GET http://localhost:5214/quests 

###
GET http://localhost:5214/quests/1

###
POST http://localhost:5214/quests
Content-Type: application/json

{
    "Name": "Głaskanie Zenia",
    "Description": "Jest słodki",
    "GenreId": 2,
    "Importance": "10",
    "StartTime": "10:13:00"
}

###
PUT http://localhost:5214/quests/2
Content-Type: application/json

{
    "Name": "Robienie algorytmiki",
    "Description": "Bedzie ciężko",
    "Genre": "Praca w domu",
    "Importance": "9",
    "StartTime": "12:13:00"
}

###
DELETE http://localhost:5214/quests/4