// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO_LIST.Api.Data;

#nullable disable

namespace TODO_LIST.Api.Data.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20240816163706_SeedGenres")]
    partial class SeedGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TODO_LIST.Api.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Codzienne"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Praca w domu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nauka"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Żywienie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hobby"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Znajomości"
                        });
                });

            modelBuilder.Entity("TODO_LIST.Api.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("TODO_LIST.Api.Entities.Quest", b =>
                {
                    b.HasOne("TODO_LIST.Api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
